# library(devtools)
# install_github('mdozmorov/MDmisc')
library(MDmisc)
pdf("Pubmed - reproducible research.pdf")
get_pubmed_graph("reproducible research")
dev.off()

pdf("Pubmed - retraction.pdf")
get_pubmed_graph("retraction")
dev.off()